// Code generated by protoc-gen-go. DO NOT EDIT.
// source: learnhelloworld.proto

/*
Package learnhelloworld is a generated protocol buffer package.

It is generated from these files:
	learnhelloworld.proto

It has these top-level messages:
	IntroRequest
	IntroResponse
*/
package learnhelloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntroRequest struct {
	IntroPerson     string `protobuf:"bytes,1,opt,name=introPerson" json:"introPerson,omitempty"`
	NumberOfFingers int32  `protobuf:"varint,2,opt,name=numberOfFingers" json:"numberOfFingers,omitempty"`
}

func (m *IntroRequest) Reset()                    { *m = IntroRequest{} }
func (m *IntroRequest) String() string            { return proto.CompactTextString(m) }
func (*IntroRequest) ProtoMessage()               {}
func (*IntroRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IntroRequest) GetIntroPerson() string {
	if m != nil {
		return m.IntroPerson
	}
	return ""
}

func (m *IntroRequest) GetNumberOfFingers() int32 {
	if m != nil {
		return m.NumberOfFingers
	}
	return 0
}

type IntroResponse struct {
	IntroMachine string `protobuf:"bytes,1,opt,name=introMachine" json:"introMachine,omitempty"`
}

func (m *IntroResponse) Reset()                    { *m = IntroResponse{} }
func (m *IntroResponse) String() string            { return proto.CompactTextString(m) }
func (*IntroResponse) ProtoMessage()               {}
func (*IntroResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IntroResponse) GetIntroMachine() string {
	if m != nil {
		return m.IntroMachine
	}
	return ""
}

func init() {
	proto.RegisterType((*IntroRequest)(nil), "learnhelloworld.IntroRequest")
	proto.RegisterType((*IntroResponse)(nil), "learnhelloworld.IntroResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Intro service

type IntroClient interface {
	// Introduce each other
	Intro(ctx context.Context, in *IntroRequest, opts ...grpc.CallOption) (*IntroResponse, error)
}

type introClient struct {
	cc *grpc.ClientConn
}

func NewIntroClient(cc *grpc.ClientConn) IntroClient {
	return &introClient{cc}
}

func (c *introClient) Intro(ctx context.Context, in *IntroRequest, opts ...grpc.CallOption) (*IntroResponse, error) {
	out := new(IntroResponse)
	err := grpc.Invoke(ctx, "/learnhelloworld.Intro/Intro", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Intro service

type IntroServer interface {
	// Introduce each other
	Intro(context.Context, *IntroRequest) (*IntroResponse, error)
}

func RegisterIntroServer(s *grpc.Server, srv IntroServer) {
	s.RegisterService(&_Intro_serviceDesc, srv)
}

func _Intro_Intro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntroServer).Intro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/learnhelloworld.Intro/Intro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntroServer).Intro(ctx, req.(*IntroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Intro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "learnhelloworld.Intro",
	HandlerType: (*IntroServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Intro",
			Handler:    _Intro_Intro_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learnhelloworld.proto",
}

func init() { proto.RegisterFile("learnhelloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x49, 0x4d, 0x2c,
	0xca, 0xcb, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0x8a, 0xe2, 0xe2, 0xf1, 0xcc, 0x2b, 0x29, 0xca, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe0, 0xe2, 0xce, 0x04, 0xf1, 0x03, 0x52, 0x8b, 0x8a,
	0xf3, 0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x34, 0xb8, 0xf8, 0xf3,
	0x4a, 0x73, 0x93, 0x52, 0x8b, 0xfc, 0xd3, 0xdc, 0x32, 0xf3, 0xd2, 0x53, 0x8b, 0x8a, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x58, 0x83, 0xd0, 0x85, 0x95, 0x8c, 0xb9, 0x78, 0xa1, 0x66, 0x17, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x0a, 0x29, 0x71, 0xf1, 0x80, 0x4d, 0xf2, 0x4d, 0x4c, 0xce, 0xc8, 0xcc, 0x4b,
	0x85, 0x9a, 0x8e, 0x22, 0x66, 0x14, 0xc8, 0xc5, 0x0a, 0xd6, 0x24, 0xe4, 0x01, 0x63, 0xc8, 0xea,
	0xa1, 0xfb, 0x05, 0xd9, 0xc5, 0x52, 0x72, 0xb8, 0xa4, 0x21, 0x96, 0x2a, 0x31, 0x24, 0xb1, 0x81,
	0xfd, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xd1, 0x06, 0x92, 0x14, 0x01, 0x00, 0x00,
}
